CREATE TABLE [dbo].[Transactions](
	[TRANSACTION_ID] [int] NOT NULL,
	[TRANSACTION_DATE] [nvarchar](50) NOT NULL,
	[ACCOUNT_NUMBER] [int] NOT NULL,
	[QUANTITY] [tinyint] NOT NULL,
	[PRODUCT_CODE] [smallint] NOT NULL,
	[PRODUCT_CATEGORY] [nvarchar](50) NOT NULL,
	[PRODUCT_NAME] [nvarchar](50) NOT NULL,
	[PRODUCT_PRICE] [float] NOT NULL,
	[LINE_TOTAL] [float] NOT NULL,
	[PAYMENT_TYPE] [nvarchar](50) NOT NULL,
	[CARD_NUMBER] [nvarchar](50) NULL,
	[USED_COUPON] [bit] NOT NULL,
	[USED_GIFT_CARD] [bit] NOT NULL,
	[COUPON_CODE] [nvarchar](50) MASKED WITH (FUNCTION = 'partial(0,"XXX",4)') NULL,
	[SALES_PERSON] [nvarchar](50) NOT NULL,
	[STORE_ID] [tinyint] NOT NULL
)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231237, N'2020-07-01' , 48522366, 1, 2002, N'SINK', N'Undermount Sink', 240, 240, N'CARD', N'51**-****-****-4863', 0, 0, N'0002002', N'Sam', 14)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231238, N'2020-07-01' , 70498615, 1, 1002, N'HOME_APPLIANCES', N'Refrigerator', 1000, 1000, N'CARD', N'32**-****-****-8277', 0, 0, N'0001002', N'Joe', 13)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231239, N'2020-07-01' , 28046583, 1, 5002, N'DECOR', N'Shelves', 65, 65, N'CARD', N'50**-****-****-8323', 0, 1, N'0005002', N'Sam', 14)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231240, N'2020-07-01' , 66420784, 1, 1006, N'HOME_APPLIANCES', N'Water Heater', 352, 352, N'CASH', NULL, 0, 0, N'0001006', N'Hanna', 12)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231241, N'2020-07-01' , 25554897, 1, 5003, N'DECOR', N'Tabletop', 65, 65, N'CARD', N'38**-****-****-1148', 1, 0, N'0005003', N'Joe', 13)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231242, N'2020-07-01' , 94257357, 1, 3004, N'HOME', N'Storage', 440, 440, N'CARD', N'43**-****-****-4769', 0, 0, N'0003004', N'Joe', 13)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231243, N'2020-07-01' , 28338563, 1, 3002, N'HOME', N'Sofa', 585, 585, N'CARD', N'47**-****-****-8650', 0, 1, N'0003002', N'Hanna', 12)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231244, N'2020-07-01' , 21754882, 1, 6001, N'KITCHEN_ACCESSORIES', N'Electric Cooker', 90, 90, N'CARD', N'30**-****-****-5789', 1, 0, N'0006001', N'Hanna', 12)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231245, N'2020-07-01' , 53988084, 1, 5003, N'DECOR', N'Tabletop', 65, 65, N'CARD', N'48**-****-****-4326', 0, 1, N'0002003', N'Joe', 13)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231246, N'2020-07-01' , 71369790, 1, 6001, N'KITCHEN_ACCESSORIES', N'Electric Cooker', 90, 90, N'CARD', N'50**-****-****-3484', 0, 0, NULL, N'Sam', 14)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231247, N'2020-07-01' , 90021853, 1, 2004, N'SINK', N'Laundry Tubs', 35, 35, N'CARD', N'36**-****-****-7289', 0, 1, NULL, N'Joe', 13)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231248, N'2020-07-01' , 10753519, 1, 4005, N'GARDENING', N'Pots', 25, 25, N'CARD', N'46**-****-****-5959', 1, 1, N'GARDENING2-C', N'Sam', 14)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231249, N'2020-07-01' , 19811808, 1, 6002, N'KITCHEN_ACCESSORIES', N'Knife set', 55, 55, N'CASH', NULL, 0, 0, NULL, N'Sam', 14)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231250, N'2020-07-01' , 69582274, 1, 2002, N'SINK', N'Undermount Sink', 240, 240, N'CARD', N'55**-****-****-1072', 0, 0, NULL, N'Sam', 14)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231251, N'2020-07-01' , 27313161, 1, 5004, N'DECOR', N'Bathroom Organizer', 100, 100, N'CARD', N'48**-****-****-3301', 0, 0, NULL, N'Joe', 13)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231252, N'2020-07-01' , 94532370, 1, 3005, N'HOME', N'Media Furniture', 275, 275, N'CARD', N'41**-****-****-4647', 0, 1, NULL, N'Hanna', 12)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231253, N'2020-07-01' , 41258078, 1, 4001, N'GARDENING', N'Water Flow Meter', 40, 40, N'CARD', N'33**-****-****-7699', 0, 1, NULL, N'Hanna', 12)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231254, N'2020-07-01' , 11406434, 1, 3003, N'HOME', N'Bench', 535, 535, N'CARD', N'55**-****-****-9809', 0, 0, NULL, N'Joe', 13)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231255, N'2020-07-01' , 66981295, 1, 4002, N'GARDENING', N'Gloves', 40, 40, N'CARD', N'54**-****-****-2160', 1, 1, N'GARDENING2-C', N'Hanna', 12)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231256, N'2020-07-01' , 39524499, 1, 2001, N'SINK', N'Top Mount Sink', 430, 430, N'CARD', N'46**-****-****-2776', 1, 0, N'SINK2-C', N'Joe', 13)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231257, N'2020-07-01' , 40510847, 1, 5001, N'DECOR', N'Plants', 45, 45, N'CARD', N'57**-****-****-9005', 0, 1, NULL, N'Sam', 14)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231258, N'2020-07-01' , 87158101, 1, 5002, N'DECOR', N'Shelves', 65, 65, N'CARD', N'53**-****-****-2012', 0, 0, NULL, N'Sam', 14)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231259, N'2020-07-01' , 43819048, 1, 3002, N'HOME', N'Sofa', 585, 585, N'CARD', N'33**-****-****-2975', 0, 0, NULL, N'Sam', 14)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231260, N'2020-07-01' , 79044995, 1, 1006, N'HOME_APPLIANCES', N'Water Heater', 352, 352, N'CARD', N'43**-****-****-7648', 1, 0, N'HOME_APPLIANCES1-C', N'Joe', 13)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231261, N'2020-07-01' , 64707417, 1, 2002, N'SINK', N'Undermount Sink', 240, 240, N'CASH', NULL, 0, 1, NULL, N'Joe', 13)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231262, N'2020-07-01' , 24585953, 1, 3004, N'HOME', N'Storage', 440, 440, N'CARD', N'30**-****-****-2941', 0, 0, NULL, N'Joe', 13)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231263, N'2020-07-01' , 61463383, 1, 5001, N'DECOR', N'Plants', 45, 45, N'CARD', N'30**-****-****-1853', 0, 0, NULL, N'Joe', 13)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231264, N'2020-07-01' , 48711374, 1, 3003, N'HOME', N'Bench', 535, 535, N'CASH', NULL, 0, 1, NULL, N'Hanna', 12)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231265, N'2020-07-01' , 84120511, 1, 4003, N'GARDENING', N'Gardening Set', 30, 30, N'CARD', N'52**-****-****-2526', 1, 0, N'GARDENING2-C', N'Sam', 14)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231266, N'2020-07-01' , 53558607, 1, 2001, N'SINK', N'Top Mount Sink', 430, 430, N'CARD', N'33**-****-****-2900', 0, 1, NULL, N'Hanna', 12)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231267, N'2020-07-01' , 34301888, 1, 3004, N'HOME', N'Storage', 440, 440, N'CARD', N'41**-****-****-5088', 0, 0, NULL, N'Sam', 14)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231268, N'2020-07-01' , 58361841, 1, 3001, N'HOME', N'Chair', 40, 40, N'CASH', NULL, 1, 0, N'HOME2-C', N'Joe', 13)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231269, N'2020-07-01' , 47022751, 1, 5003, N'DECOR', N'Tabletop', 65, 65, N'CARD', N'50**-****-****-6793', 0, 0, NULL, N'Hanna', 12)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231270, N'2020-07-01' , 21462534, 1, 2001, N'SINK', N'Top Mount Sink', 430, 430, N'CARD', N'42**-****-****-4851', 0, 0, NULL, N'Hanna', 12)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231271, N'2020-07-01' , 88659046, 1, 3004, N'HOME', N'Storage', 440, 440, N'CARD', N'36**-****-****-6534', 0, 0, NULL, N'Hanna', 12)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231272, N'2020-07-01' , 52810309, 1, 3002, N'HOME', N'Sofa', 585, 585, N'CARD', N'40**-****-****-5431', 0, 0, NULL, N'Hanna', 12)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231273, N'2020-07-01' , 77757293, 1, 2002, N'SINK', N'Undermount Sink', 240, 240, N'CARD', N'57**-****-****-6966', 0, 0, NULL, N'Joe', 13)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231274, N'2020-07-01' , 77090268, 1, 1003, N'HOME_APPLIANCES', N'Water Cooler', 45, 45, N'CARD', N'53**-****-****-1192', 0, 0, NULL, N'Hanna', 12)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231275, N'2020-07-01' , 37382592, 1, 3002, N'HOME', N'Sofa', 585, 585, N'CARD', N'34**-****-****-3705', 0, 0, NULL, N'Joe', 13)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231276, N'2020-07-01' , 68062862, 1, 4001, N'GARDENING', N'Water Flow Meter', 40, 40, N'CARD', N'34**-****-****-3434', 0, 0, NULL, N'Joe', 13)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231277, N'2020-07-01' , 52175331, 5, 4005, N'GARDENING', N'Pots', 25, 125, N'CARD', N'40**-****-****-7884', 0, 0, NULL, N'Hanna', 12)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231278, N'2020-07-01' , 13449233, 1, 1005, N'HOME_APPLIANCES', N'Dishwasher', 455, 455, N'CASH', NULL, 0, 0, NULL, N'Joe', 13)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231279, N'2020-07-01' , 58655275, 1, 1002, N'HOME_APPLIANCES', N'Refrigerator', 1000, 1000, N'CARD', N'45**-****-****-5659', 0, 0, NULL, N'Sam', 14)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231280, N'2020-07-01' , 86458425, 1, 5001, N'DECOR', N'Plants', 45, 45, N'CARD', N'46**-****-****-6258', 0, 1, NULL, N'Joe', 13)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231281, N'2020-07-01' , 67744152, 1, 3005, N'HOME', N'Media Furniture', 275, 275, N'CASH', NULL, 0, 0, NULL, N'Joe', 13)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231282, N'2020-07-01' , 34363570, 1, 2002, N'SINK', N'Undermount Sink', 240, 240, N'CARD', N'57**-****-****-7872', 0, 0, NULL, N'Sam', 14)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231283, N'2020-07-01' , 81048310, 1, 6003, N'KITCHEN_ACCESSORIES', N'Dry Food Dispenser', 55, 55, N'CARD', N'38**-****-****-1716', 0, 0, NULL, N'Joe', 13)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231284, N'2020-07-01' , 15117780, 1, 4005, N'GARDENING', N'Pots', 25, 25, N'CASH', NULL, 1, 0, N'GARDENING2-C', N'Sam', 14)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231285, N'2020-07-01' , 34658037, 1, 5002, N'DECOR', N'Shelves', 65, 65, N'CARD', N'45**-****-****-6744', 1, 0, N'DECOR2-C', N'Hanna', 12)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231286, N'2020-07-01' , 72264414, 1, 1001, N'HOME_APPLIANCES', N'Freezer', 310.99, 310.99, N'CARD', N'33**-****-****-1128', 0, 1, NULL, N'Hanna', 12)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231287, N'2020-07-01' , 85175302, 1, 1001, N'HOME_APPLIANCES', N'Freezer', 310.99, 310.99, N'CARD', N'55**-****-****-5794', 0, 1, NULL, N'Sam', 14)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231288, N'2020-07-01' , 93805064, 1, 2004, N'SINK', N'Laundry Tubs', 35, 35, N'CARD', N'35**-****-****-8136', 1, 0, N'SINK1-C', N'Hanna', 12)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231289, N'2020-07-01' , 37595459, 1, 3005, N'HOME', N'Media Furniture', 275, 275, N'CARD', N'46**-****-****-8494', 1, 0, N'HOME1-C', N'Sam', 14)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231290, N'2020-07-01' , 94525011, 1, 4004, N'GARDENING', N'Trowel', 45, 45, N'CARD', N'36**-****-****-4343', 0, 0, NULL, N'Sam', 14)
GO
INSERT [dbo].[Transactions] ([TRANSACTION_ID], [TRANSACTION_DATE], [ACCOUNT_NUMBER], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [CARD_NUMBER], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID]) VALUES (231291, N'2020-07-01' , 18369167, 1, 6002, N'KITCHEN_ACCESSORIES', N'Knife set', 55, 55, N'CARD', N'53**-****-****-3585', 1, 1, N'KITCHEN_ACCESSORIES1-C', N'Joe', 13)
GO