EXECUTE AS USER = 'DataScienceUser';  
SELECT * FROM Transactions;
REVERT;  

EXECUTE AS USER = 'DataScienceUser';  
SELECT [TRANSACTION_DATE], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], [PRODUCT_NAME], [PRODUCT_PRICE], [LINE_TOTAL], [PAYMENT_TYPE], [USED_COUPON], [USED_GIFT_CARD], [COUPON_CODE], [SALES_PERSON], [STORE_ID] FROM Transactions;
REVERT;  


EXECUTE AS USER = 'Joe';  
SELECT * FROM Transactions;
REVERT;  
  
EXECUTE AS USER = 'Manager';  
SELECT * FROM Transactions;
REVERT; 