EXECUTE AS USER = 'DataScienceUser';  
SELECT * FROM Transactions;
REVERT;  

EXECUTE AS USER = 'DataScienceUser';  
SELECT [TRANSACTION_DATE], [QUANTITY], [PRODUCT_CODE], [PRODUCT_CATEGORY], 
    [PRODUCT_NAME], [COUPON_CODE], [LINE_TOTAL], [PAYMENT_TYPE], 
    [USED_COUPON], [USED_GIFT_CARD], [PRODUCT_PRICE], [SALES_PERSON], [STORE_ID] 
FROM Transactions
ORDER BY [USED_COUPON], [COUPON_CODE] DESC;
REVERT;  


EXECUTE AS USER = 'Joe';  
SELECT SALES_PERSON, * FROM Transactions;
REVERT;  
  
EXECUTE AS USER = 'Manager';  
SELECT SALES_PERSON, * FROM Transactions;
REVERT; 